# Generated by Django 5.1.3 on 2025-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_sms2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sms_text', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='chat_sms',
        ),
    ]
