# Generated by Django 5.1.3 on 2025-01-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hart_app', '0002_chat_sms2_delete_chat_sms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat_sms2',
            new_name='chat_sms',
        ),
    ]
