# Generated by Django 5.1.3 on 2025-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hart_app', '0005_rename_hart_app_chat_sms_chat_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='hart_app_chat_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sms_text', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
