# Generated by Django 5.1.3 on 2025-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hart_app', '0006_hart_app_chat_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat_sms',
        ),
        migrations.DeleteModel(
            name='hart_app_chat_sms',
        ),
    ]
