# Generated by Django 5.1.3 on 2025-01-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hart_app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat_sms',
        ),
    ]
